a=c(1,5,7,8,9,6,4,9,5,8,9,6)
cat("Range: ",range(a),"\n")
cat("Summary: ",summary(a),"\n")
cat("Mean: ",mean(a),"\n")
cat("Variance: ",var(a),"\n")
cat("Standard Deviation: ",sqrt(var(a)),"\n")
#print(hist(a))
#print(boxplot(a))
#print(scatter.smooth(a))