x=c(9,1,5,7,4,3)
cat("x=",x)
y=c(2,100)
cat("\ny=",y)
cat("\nx*y=",x*y)
cat("\n",sqrt(x),"\n")
A=matrix(nrow=2,ncol=3,data=c(9,2,1,7,5,4))
print(A)
B=t(A)
print(B)
print(A%*%B)
a=list(3,1,"Hello",4.1,TRUE,c(3,1,5),-3+4i)
print(a[[1]])
r=data.frame(1:3,c("Mahesh","Ganesh","Mangesh"),c(21,22,23))
colnames(fr)=c("Roll No.","Name","Age")
print(fr)
print(rownames(fr))