print("Demonstration of file handling")
f=open("JK.txt","rt")
fo=open("out1.txt","w")
print("Reading file character by character")
while True:
    s=f.read(1)
    fo.write(s)
    if s=="":
        break
    print(s)
f.close()
fo.close()
f=open("JK.txt","rt")
fo=open("out2.txt","w")
print("\nReading file line by line")
while True:
    s=f.readline()
    fo.writelines(s)
    if s=="":
        break
    print(s)
f.close()
fo.close()
f=open("JK.txt","rt")
fo=open("out3.txt","w")
print("\nReading file at once")
s=f.readlines()
fo.writelines(s)
print(s)
f.close()
fo.close()
print("\n\n\nDemonstration of append mode")
f=open("sample.txt","a")
f.write("This is the additional text")
f.close
j=open("sample.txt","r")
s=j.read()
print(s)
j.close()
print("\n\n\nDemonstration of binary mode")
k=open("famt.jpg","rb")
f=open("NewBinary.jpg","wb")
s=k.read()
f.write(s)
k.close()
f.close()
